import Head from 'next/head';
import Hero from '../components/Hero';
import Projects from '../components/Projects';
import Instagram from '../components/Instagram';
import Portfolio from '../components/Portfolio';
import Contact_Details from '../components/Contact_Details';
import About from '../components/About';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Personal Details</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='custom img'>
        <div >
        <div className='flex items-left'>
        <Hero heading='Full - Stack Developer' message='To become a successful professional in a challenging workplace to enhance my knowledge in the field of information Technology as well as work towards betterment of on organization.' />
        </div>
      </div>
      <Contact_Details/>
      <About/>
    </div>
</div>
  );
}
